SD_PATH=$({SDCARD_PATH})
TMPDIR=$({TEMP_DIR})
HOME=$({START_DIR})
APP_USER_ID=$({APP_USER_ID})
SDK=$({ANDROID_SDK})
Package_name=$({PACKAGE_NAME})
Version_Name=$({PACKAGE_VERSION_NAME})
Version_code=$({PACKAGE_VERSION_CODE})
PREFIX=$({TOOLKIT})
Have_ROOT=$({ROOT_PERMISSION})
ANDROID_UID=$({ANDROID_UID})
DATA_DIR=${HOME%/${Package_name}*}
PATH0=$PATH
Pages=$({TOOLKIT})/pages
BUSYBOX=$({BUSYBOX})
binariesPath=$({nativeLibPath})
ShellScript=$({TOOLKIT})/kr-script
PeiZhi_File=$({START_DIR})/Configuration_File
Data_Dir=$({TOOLKIT})/Data_Dir
ELF1_Path=$({TOOLKIT})/bin
ELF2_Path=$({TOOLKIT})/bin/xbin
ELF3_Path=$({TOOLKIT})/xbin
ELF4_Path=$({TOOLKIT})/busybox
which="toybox which"
data_MD5=$({TOOLKIT})/kr-script/init_all_MD5.sh
Load=$({TOOLKIT})/kr-script/init_data.sh
core=$({TOOLKIT})/kr-script/Util_Functions.sh
Bin_MT1=$DATA_DIR/bin.mt.plus/files/term/usr/bin
Bin_MT2=$DATA_DIR/bin.mt.plus/files/term/usr/lib
Bin_MT3=$DATA_DIR/bin.mt.plus.canary/files/term/usr/bin
Bin_MT4=$({TOOLKIT})
TMP=/data/local/tmp

START_DIR=$({START_DIR})
TEMP_DIR=$({TEMP_DIR})
ANDROID_SDK=$({ANDROID_SDK})
MAGISK_PATH=$({MAGISK_PATH})

